language: node_js
sudo: false
node_js:
  - '4.3'
  - '4.4'

cache:
  directories:
    - $(npm root -g)
    - node_modules
    - deep_modules
    - $(npm config get prefix)/bin/deepify
    - $(npm config get prefix)/bin/jspm
    - $(npm config get prefix)/bin/karma
    - $(npm config get prefix)/bin/_mocha
    - $(npm config get prefix)/bin/istanbul

env:
  # To disable interactive user interaction like prompts in terminal (an default value is always chosen)
  - DEEP_NO_INTERACTION=1
  # Paralize backend and fronted test
  - TEST_SUITE=backend
  - TEST_SUITE=frontend

branches:
  only:
    - master
    - dev
    - stage
    - test

before_install:
  - cp bin/test/package.json .

after_success:
  - npm run coverage
