language: node_js
sudo: required
node_js:
  - '4.3'
  - '7.0'
cache:
  edge: true
  directories:
    - $(npm root -g)
    - node_modules
    - deep_modules
    - $(npm config get prefix)/bin
branches:
  only:
    - master
    - dev
    - stage
    - test
before_install:
  - cp bin/test/package.json .
after_success:
  - npm run coverage
after_script:
  - npm run remove-coverage
env:
  global:
    - E2E_TESTING=none
    - DEEP_NO_INTERACTION=1
    - secure: 
        EgNSWuexHnvT9NqXH0kw107IZcxm1XokrYYhBOZkO4kuxu+1kQkTiQLmKVOWGuWEViP6d48ZQDF4Up9CPyExXNhLTW/SCMQZ4rvYeuXkgFYXm25gRQ1Fu7a2z/gh9fJgfj9yRBolOTt4TzWjtiv7fjilpYv1KWCNAULQ8kAryMWllpEu83Y/LphiAQH15UBdn72KzUF1Wz/57mNZMm+yffxppoqbqibnBVETXy9EFKeVaopEDKfP72jMU6nAV22x+YKqrAo2ArCt9x8iupDSnUUhodMFCXc0IH19L1+suJOoMhHME1BZQjnluV1HoeNDx+lK1tT6NOw5X13sm4/usuMui3QUiOYV2No294/ssOEHmXWy8baRmvaTqZ6hIPLlDZHfGCQ5TdJwtASEeky2l/6VjIvsQflFGKS3XUvoOUnfSK8HfqeoIC1E76/C5d13owwpOiaPrlrMvj3hyr17rsOnGvGDJbJGj6NuwLtIscP31FPutsy3OOJXu5E1hzIU/pYVznbIvL1fxdOJKP6vFO5CePyoKvjB5+2epCdfgDiRvm8r8PRx4XoMaSRtvO8WjRmtc5CGOM4IbfMZHeqG+SA/va5AR+Fv07qq+qxQpwX8FYrPMj9iHi1yW4tlkHg7FCJy+nzXTNhCw+uC0/Ry9Zn9DL8hYlWnbB5C76qQks0=