language: node_js
sudo: false
node_js:
  - '4.3'
  - '5.10'

cache:
  directories:
    - $(npm root -g)

branches:
  only:
    - master
    - dev
    - stage
    - test

before_install:
  - npm run prepare

after_success:
  - npm run coverage
