language: node_js
sudo: false
node_js:
  - '0.10'
  - '0.11'
  - '0.12'
  - '4.0'
  - '4.1'
  - '4.2'
  - '4.3'
  - '5.0'
  - '5.1'
  - '5.2'
  - '5.3'
  - '5.4'
  - '5.5'
  - '5.6'
  - '5.7'
  - '5.8'
  - '5.9'
  - '5.10'

cache:
  directories:
    - $(npm root -g)
    - node_modules

branches:
  only:
    - master
    - dev
    - stage
    - test

before_install:
  - cp bin/test/package.json .
  - npm run prepare

after_success:
  - npm run coverage

env:
  global:
    - E2E_TESTING=none
