language: node_js
sudo: false
node_js:
  - '4.3'
  - '5.0'
  - '5.1'
  - '5.9'
  - '5.10'

cache:
  directories:
    - $(npm root -g)
    - node_modules

branches:
  only:
    - master
    - dev
    - stage
    - test

before_install:
  - cp bin/test/package.json .
  - npm run prepare

after_success:
  - npm run coverage
