language: node_js
sudo: false
node_js:
  - '4.3'
  - '4.4'

cache:
  edge: true
  directories:
    - $(npm root -g)
    - node_modules
    - deep_modules
    - $(npm config get prefix)/bin/deepify
    - $(npm config get prefix)/bin/jspm
    - $(npm config get prefix)/bin/karma
    - $(npm config get prefix)/bin/_mocha
    - $(npm config get prefix)/bin/istanbul
    - $(npm config get prefix)/bin/istanbul-combine
    - $(npm config get prefix)/bin/codacy-coverage
    - $(npm config get prefix)/bin/protractor

branches:
  only:
    - master
    - dev
    - stage
    - test

before_install:
  - cp bin/test/package.json .

after_success:
  - npm run coverage

env:
  matrix:
    # Parallelize backend and fronted test
    - TEST_SUITE=backend
    - TEST_SUITE=frontend
