language: node_js
sudo: false
node_js:
  - '0.10'
  - '0.11'
  - '0.12'
  - '4.3'
  - '5.0'
  - '5.1'
  - '5.9'
  - '5.10'

cache:
  directories:
    - $(npm root -g)
    - node_modules

branches:
  only:
    - master
    - dev
    - stage
    - test
env:
    global:
       # SAUCE_USERNAME=[secured]
       - secure: o1ni6XQ2naZvik5USOdd0CBkcAVhSmYcumEol4/gX+d7Rq3/h20B5WeDEKq55mOkPRq5WLPZfdE5KoDHLvz4qNs+pmwAUNy5lvbhs2RU8DvJVzJAHSoyKCXwJr/kmACjDH0/95FyUrCtml4b7gpFRCtTfhhnUCQDtdXO64znvQqN2Yyd/igNZ6lTs6nK7GnzKYChhF1WsIs9ROLY05yGlWy87JWW2xwMtDTP4ufF1EqlHAT6taDcV+a+6iywkFA9EBo7t5+ZO9m2IfHHEvTBbePvUNMTPf8K07EHZM83+b6sjYU/ucYGzHg0E+YmAsnmy1ALjf+6KyOz+UnSm9zC0htMHH1TzS+rNK6KfYELlTIiIB2wYgKNwnrWsYk21+EkzKE+0J+7ytCtZUbcI8NbFeZ9l73tXbNT5n5ATBSY9rpG3CpaKNvXwlCO0vPVctTuk20q92aKcVvFy7/iu5UhUoEY5b/yN4f0f9fcuRr304FwifHGUiCs3kTQ7VDz5TKOSjjTptjcAq3hMMXZqoVFrkuH1IWUCUGycim/keojpgz419FatkDnroBLknWrqjvXXVIqr2ZROtKZVoq0eHXAgeDdqkomzigHKIEJDzTwXEC9TtUDQ7HhTA3P+Vk7cIp6MGuq+Xi6dW0M6jOJ/VMU5jfAJ0yX//1seSVTKWBGkOo=
       # SAUCE_ACCESS_KEY=[secured]
       - secure: f+HaFd/PrMhX0XyYQudPhOpjGWPXN/jjiV9nzMxr8U14v0ej3f2feWoz/2MW//C44bGgHtpcm83k2+GwW2FTOTt4AANb/KKhAoBiWnLei/WH7QNNm8D+MrNBluOjKAkcD67j1redfFO6buUJ7nSCcRtuYQ53n6xfs7KWORHxHlg3n7dzM+f5qMnFfdjIUbHH90eTORSrmYS6t8a2niGUxVY22JTuTCKFRx2dhD9w84LiTRvK/do6ZAVuoSzbXhcBap0Yuv84mUWydLsaJqskfmZ4z6ViYhr+cCqcmBsmc/12XljqwyPX0YonKrrzw17xw6ofCpBwUB6x+UH4iqd/vdP8F1dhEgLXpar58ZsWf9g/zflmTdnkw7KNeshTVUsHq9X5C7t43VyRPQZ5Eo6xOAsSVP/Fd9OdNne/bInUsJmIURUTEQBH6hIVyQ7F3OCXCzpOUJOyoyc6DO0tDGMxz4SToFY1bTtOhGqgR1ErruI3H7lpMVRRgrxBRhoY+E7N6Ak8Ypun/SqY9F1p6QIgpisVuUkfFUxbBOZ4Lhojk6wigZ3GKKCEQUV6MdRVBaQ7hSO1xW4AGu5s96BZzz2VrKH6MxxiNQ65b0V8ZgAYMb3fzsbHiTrgNC1Kgb4r/bpbBRsk0vhRZZ8jIau2F+dxsrMQGMcTSpvyplfWNsoK4Hg=
before_install:
  - cp bin/test/package.json .
  - npm run prepare

after_success:
  - npm run coverage
